### ISSUE TITLE
Error at ubuntu 20.04

### ISSUE THREAD

**Issue by Hamilkar247** [yash10102002/electron-react-TODO-app#1]
On ubuntu i cannot run that program - I have had that output at my console
$ npm run start

> electron-todo-app@0.1.0 start
> concurrently "SET BROWSER=none && npm run react-start" "wait-on http://localhost:3000 && electron ."

[0] /bin/sh: 1: SET: not found
[0] SET BROWSER=none && npm run react-start exited with code 127
^C[1] wait-on http://localhost:3000 && electron . exited with code SIGINT

**Comment by Hamilkar247** [comment]
ok when i change in package.json from `SET BROWSER` to `set BROWSER` i have other problem - I have tracktrace 

`> electron-todo-app@0.1.0 start
> concurrently "set BROWSER=none && npm run react-start" "wait-on http://localhost:3000 && electron ."

[0] 
[0] > electron-todo-app@0.1.0 react-start
[0] > react-scripts start
[0] 
[0] (node:256056) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
[0] Update this package.json to use a subpath pattern like "./*".
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] ℹ ｢wds｣: Project is running at http://192.168.0.135/
[0] ℹ ｢wds｣: webpack output is served from 
[0] ℹ ｢wds｣: Content not from webpack is served from /home/matball-ssd/Projects/electron-react-TODO-app/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0] 
[0] Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:67:19)
[0]     at Object.createHash (node:crypto:130:10)
[0]     at module.exports (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/util/createHash.js:135:53)
[0]     at NormalModule._initBuildHash (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:417:16)
[0]     at handleParseError (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:471:10)
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:503:5
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:358:12
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[0]     at iterateNormalLoaders (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[0]     at iterateNormalLoaders (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[0] /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/react-scripts/scripts/start.js:19
[0]   throw err;
[0]   ^
[0] 
[0] Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:67:19)
[0]     at Object.createHash (node:crypto:130:10)
[0]     at module.exports (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/util/createHash.js:135:53)
[0]     at NormalModule._initBuildHash (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:417:16)
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:452:10
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/webpack/lib/NormalModule.js:323:13
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[0]     at context.callback (/home/matball-ssd/Projects/electron-react-TODO-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[0]     at /home/matball-ssd/Projects/electron-react-TODO-app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
[0]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[0]   library: 'digital envelope routines',
[0]   reason: 'unsupported',
[0]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[0] }
[0] set BROWSER=none && npm run react-start exited with code 1
`

**Comment by YashKalavadiya** [comment]
you can do
BROWSER=none 
don't use SET/set
